import type { Metadata } from "next";
import "./global.css";
import { inter } from "./fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} bg-gradient-to-b from-stone-800 to-stone-950 text-stone-300`}
            >
                {children}
            </body>
        </html>
    );
}
